In [24]:
# TESTING CODE WITH 5 CLIENTS, SINCE THERE ARE CALCULATIONS INVOLVING PERCENTILES

from collections import OrderedDict
import torch

# First OrderedDict object
model_parameters1 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3400,  0.1648, -0.0120,  0.2103,  0.2675,  0.1745],
                                         [ 0.2891,  0.2614, -0.1232, -0.0202,  0.5096,  0.6269]])),
    ('_module.fc1.bias', torch.tensor([-0.1213,  0.3632])),
    ('_module.fc2.weight', torch.tensor([[ 0.5619,  0.0126],
                                         [ 0.5260, -0.4331],
                                         [ 0.6782, -0.5148]])),
    ('_module.fc2.bias', torch.tensor([-0.4159,  0.0047,  0.6919])),
    ('_module.groupnorm.weight', torch.tensor([0.6429, 1.2070])),
    ('_module.groupnorm.bias', torch.tensor([ 0.2980, -0.3828]))
])

# Second OrderedDict object
model_parameters2 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3462,  0.1719, -0.0215,  0.2117,  0.2747,  0.1678],
                                         [ 0.3037,  0.2656, -0.1243, -0.0284,  0.5138,  0.6400]])),
    ('_module.fc1.bias', torch.tensor([-0.2414,  0.3605])),
    ('_module.fc2.weight', torch.tensor([[-0.4925, -0.2702],
                                         [ 0.0939, -0.7728],
                                         [ 0.0884, -0.3885]])),
    ('_module.fc2.bias', torch.tensor([-0.3595,  0.0375,  0.5166])),
    ('_module.groupnorm.weight', torch.tensor([0.7792, 1.2446])),
    ('_module.groupnorm.bias', torch.tensor([-0.1800, -0.4572]))
])

# Third OrderedDict object
model_parameters3 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3500,  0.1748, -0.0220,  0.2203,  0.2775,  0.1845],
                                         [ 0.2991,  0.2714, -0.1332, -0.0302,  0.5196,  0.6369]])),
    ('_module.fc1.bias', torch.tensor([-0.1313,  0.3732])),
    ('_module.fc2.weight', torch.tensor([[ 0.5719,  0.0226],
                                         [ 0.5360, -0.4431],
                                         [ 0.6882, -0.5248]])),
    ('_module.fc2.bias', torch.tensor([-0.4259,  0.0147,  0.7019])),
    ('_module.groupnorm.weight', torch.tensor([0.6529, 1.2170])),
    ('_module.groupnorm.bias', torch.tensor([ 0.3080, -0.3928]))
])

# Fourth OrderedDict object
model_parameters4 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3600,  0.1848, -0.0320,  0.2303,  0.2875,  0.1945],
                                         [ 0.3091,  0.2814, -0.1432, -0.0402,  0.5296,  0.6469]])),
    ('_module.fc1.bias', torch.tensor([-0.1413,  0.3832])),
    ('_module.fc2.weight', torch.tensor([[ 0.5819,  0.0326],
                                         [ 0.5460, -0.4531],
                                         [ 0.6982, -0.5348]])),
    ('_module.fc2.bias', torch.tensor([-0.4359,  0.0247,  0.7119])),
    ('_module.groupnorm.weight', torch.tensor([0.6629, 1.2270])),
    ('_module.groupnorm.bias', torch.tensor([ 0.3180, -0.4028]))
])

# Fifth OrderedDict object
model_parameters5 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3700,  0.1948, -0.0420,  0.2403,  0.2975,  0.2045],
                                         [ 0.3191,  0.2914, -0.1532, -0.0502,  0.5396,  0.6569]])),
    ('_module.fc1.bias', torch.tensor([-0.1513,  0.3932])),
    ('_module.fc2.weight', torch.tensor([[ 0.5919,  0.0426],
                                         [ 0.5560, -0.4631],
                                         [ 0.7082, -0.5448]])),
    ('_module.fc2.bias', torch.tensor([-0.4459,  0.0347,  0.7219])),
    ('_module.groupnorm.weight', torch.tensor([0.6729, 1.2370])),
    ('_module.groupnorm.bias', torch.tensor([ 0.3280, -0.4128]))
])

# Combine all OrderedDict objects into a list of tuples
combined_list = [model_parameters1, model_parameters2, model_parameters3, model_parameters4, model_parameters5]

# If you want an array, you can use numpy to convert the list to an array
# import numpy as np
# combined_array = np.array(combined_list)

In [25]:
combined_list

[OrderedDict([('_module.fc1.weight',
               tensor([[ 0.3400,  0.1648, -0.0120,  0.2103,  0.2675,  0.1745],
                       [ 0.2891,  0.2614, -0.1232, -0.0202,  0.5096,  0.6269]])),
              ('_module.fc1.bias', tensor([-0.1213,  0.3632])),
              ('_module.fc2.weight',
               tensor([[ 0.5619,  0.0126],
                       [ 0.5260, -0.4331],
                       [ 0.6782, -0.5148]])),
              ('_module.fc2.bias', tensor([-0.4159,  0.0047,  0.6919])),
              ('_module.groupnorm.weight', tensor([0.6429, 1.2070])),
              ('_module.groupnorm.bias', tensor([ 0.2980, -0.3828]))]),
 OrderedDict([('_module.fc1.weight',
               tensor([[ 0.3462,  0.1719, -0.0215,  0.2117,  0.2747,  0.1678],
                       [ 0.3037,  0.2656, -0.1243, -0.0284,  0.5138,  0.6400]])),
              ('_module.fc1.bias', tensor([-0.2414,  0.3605])),
              ('_module.fc2.weight',
               tensor([[-0.4925, -0.2702],
            

In [26]:
import torch
from collections import OrderedDict
from typing import List

def submodel_two(models: List[OrderedDict]) -> OrderedDict:
    # Helper function to calculate IQR-based non-outliers for a list of values
    def non_outlier_values(values):
        q1, q3 = torch.quantile(torch.tensor(values), torch.tensor([0.25, 0.75]))
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        return [v for v in values if v >= lower_bound and v <= upper_bound]

    # Initialize a dictionary to store sums and counts for averaging
    sums = OrderedDict((key, torch.zeros_like(models[0][key])) for key in models[0])
    counts = OrderedDict((key, torch.zeros_like(models[0][key])) for key in models[0])

    # Iterate through each key and each element in the tensors
    for key in models[0].keys():
        for i in range(models[0][key].numel()):
            # Extract the same element from all models
            values = [model[key].view(-1)[i].item() for model in models]

            # Calculate non-outlier values
            non_outliers = non_outlier_values(values)

            # Update sums and counts
            if non_outliers:
                sums[key].view(-1)[i] = sum(non_outliers)
                counts[key].view(-1)[i] = len(non_outliers)

    # Calculate element-wise averages for non-outliers and remove the '_module' prefix
    averages = OrderedDict()
    for key in sums.keys():
        new_key = key.replace('_module.', '')  # Remove '_module.' prefix
        with torch.no_grad():  # Ensure no gradient is computed during division
            averages[new_key] = sums[key] / counts[key].clamp(min=1)  # Avoid division by zero

    return averages

averaged_values = submodel_two(combined_list)

In [27]:
averaged_values

OrderedDict([('fc1.weight',
              tensor([[ 0.3532,  0.1782, -0.0259,  0.2226,  0.2809,  0.1852],
                      [ 0.3040,  0.2742, -0.1354, -0.0338,  0.5224,  0.6415]])),
             ('fc1.bias', tensor([-0.1363,  0.3747])),
             ('fc2.weight',
              tensor([[ 0.5769,  0.0276],
                      [ 0.5410, -0.4481],
                      [ 0.6932, -0.5298]])),
             ('fc2.bias', tensor([-0.4309,  0.0233,  0.7069])),
             ('groupnorm.weight', tensor([0.6579, 1.2265])),
             ('groupnorm.bias', tensor([ 0.3130, -0.3978]))])

In [28]:
# TESTING CODE WITH 2 CLIENTS, SINCE THERE ARE CALCULATIONS INVOLVING PERCENTILES

from collections import OrderedDict
import torch

# First OrderedDict object
model_parameters1 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3400,  0.1648, -0.0120,  0.2103,  0.2675,  0.1745],
                                         [ 0.2891,  0.2614, -0.1232, -0.0202,  0.5096,  0.6269]])),
    ('_module.fc1.bias', torch.tensor([-0.1213,  0.3632])),
    ('_module.fc2.weight', torch.tensor([[ 0.5619,  0.0126],
                                         [ 0.5260, -0.4331],
                                         [ 0.6782, -0.5148]])),
    ('_module.fc2.bias', torch.tensor([-0.4159,  0.0047,  0.6919])),
    ('_module.groupnorm.weight', torch.tensor([0.6429, 1.2070])),
    ('_module.groupnorm.bias', torch.tensor([ 0.2980, -0.3828]))
])

# Second OrderedDict object
model_parameters2 = OrderedDict([
    ('_module.fc1.weight', torch.tensor([[ 0.3462,  0.1719, -0.0215,  0.2117,  0.2747,  0.1678],
                                         [ 0.3037,  0.2656, -0.1243, -0.0284,  0.5138,  0.6400]])),
    ('_module.fc1.bias', torch.tensor([-0.2414,  0.3605])),
    ('_module.fc2.weight', torch.tensor([[-0.4925, -0.2702],
                                         [ 0.0939, -0.7728],
                                         [ 0.0884, -0.3885]])),
    ('_module.fc2.bias', torch.tensor([-0.3595,  0.0375,  0.5166])),
    ('_module.groupnorm.weight', torch.tensor([0.7792, 1.2446])),
    ('_module.groupnorm.bias', torch.tensor([-0.1800, -0.4572]))
])

# Combine all OrderedDict objects into a list of tuples
combined_list = [model_parameters1, model_parameters2]

# If you want an array, you can use numpy to convert the list to an array
# import numpy as np
# combined_array = np.array(combined_list)

In [29]:
combined_list

[OrderedDict([('_module.fc1.weight',
               tensor([[ 0.3400,  0.1648, -0.0120,  0.2103,  0.2675,  0.1745],
                       [ 0.2891,  0.2614, -0.1232, -0.0202,  0.5096,  0.6269]])),
              ('_module.fc1.bias', tensor([-0.1213,  0.3632])),
              ('_module.fc2.weight',
               tensor([[ 0.5619,  0.0126],
                       [ 0.5260, -0.4331],
                       [ 0.6782, -0.5148]])),
              ('_module.fc2.bias', tensor([-0.4159,  0.0047,  0.6919])),
              ('_module.groupnorm.weight', tensor([0.6429, 1.2070])),
              ('_module.groupnorm.bias', tensor([ 0.2980, -0.3828]))]),
 OrderedDict([('_module.fc1.weight',
               tensor([[ 0.3462,  0.1719, -0.0215,  0.2117,  0.2747,  0.1678],
                       [ 0.3037,  0.2656, -0.1243, -0.0284,  0.5138,  0.6400]])),
              ('_module.fc1.bias', tensor([-0.2414,  0.3605])),
              ('_module.fc2.weight',
               tensor([[-0.4925, -0.2702],
            

In [30]:
import torch
from collections import OrderedDict
from typing import List

def submodel_two(models: List[OrderedDict]) -> OrderedDict:
    # Helper function to calculate IQR-based non-outliers for a list of values
    def non_outlier_values(values):
        q1, q3 = torch.quantile(torch.tensor(values), torch.tensor([0.25, 0.75]))
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        return [v for v in values if v >= lower_bound and v <= upper_bound]

    # Initialize a dictionary to store sums and counts for averaging
    sums = OrderedDict((key, torch.zeros_like(models[0][key])) for key in models[0])
    counts = OrderedDict((key, torch.zeros_like(models[0][key])) for key in models[0])

    # Iterate through each key and each element in the tensors
    for key in models[0].keys():
        for i in range(models[0][key].numel()):
            # Extract the same element from all models
            values = [model[key].view(-1)[i].item() for model in models]

            # Calculate non-outlier values
            non_outliers = non_outlier_values(values)

            # Update sums and counts
            if non_outliers:
                sums[key].view(-1)[i] = sum(non_outliers)
                counts[key].view(-1)[i] = len(non_outliers)

    # Calculate element-wise averages for non-outliers and remove the '_module' prefix
    averages = OrderedDict()
    for key in sums.keys():
        new_key = key.replace('_module.', '')  # Remove '_module.' prefix
        with torch.no_grad():  # Ensure no gradient is computed during division
            averages[new_key] = sums[key] / counts[key].clamp(min=1)  # Avoid division by zero

    return averages

averaged_values = submodel_two(combined_list)

In [31]:
averaged_values

OrderedDict([('fc1.weight',
              tensor([[ 0.3431,  0.1684, -0.0168,  0.2110,  0.2711,  0.1711],
                      [ 0.2964,  0.2635, -0.1238, -0.0243,  0.5117,  0.6335]])),
             ('fc1.bias', tensor([-0.1813,  0.3619])),
             ('fc2.weight',
              tensor([[ 0.0347, -0.1288],
                      [ 0.3100, -0.6029],
                      [ 0.3833, -0.4517]])),
             ('fc2.bias', tensor([-0.3877,  0.0211,  0.6043])),
             ('groupnorm.weight', tensor([0.7111, 1.2258])),
             ('groupnorm.bias', tensor([ 0.0590, -0.4200]))])

In [ ]:
# TESTING CODE ON 5 OR 2 CLIENTS BOTH WORKED!